
# Possibility to change the separator between the sortable field and the direction (ASC or DESC). Default value is : (colon) - can be changed to e.g. | by writing
#sort:
#  direction:
#    separator: \|

# Pagination settings
pagination:
  #  # encryptionKey needs to be one of the following sizes: 128, 192 or 256 bits - in the example below it is 128 bit (= 16 bytes)
  #  encryptionKey: xyz123wersdgf354
  #  config:
  #    # Change name of cursor parameter name
  #    cursorName:
  #    # Change name of pageSize parameter name
  #    pageSizeName:
  #    # Change name of current-page header name
  #    currentPageName:
  #    # Change name of next-page header name
  #    nextPageName:
  #    # Change name of previous-page header name
  #    previousPageName:
  #    # Change name of first-page header name
  #    firstPageName:
  #  # Possibility to change the default pagination size. If not specified all results will be returned as default
  defaultPageSize: 20

spring:
  application:
    name: dcsa-ctk-consumer
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dcsa_openapi?currentSchema=dcsa_im_v3_0
    dbname: dcsa_openapi
    properties:
      schema: dcsa_im_v3_0
    username: dcsa_db_owner
    password: 9c072fe8-c59c-11ea-b8d1-7b6577e9f3f5

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dcsa.eu.auth0.com/
  webflux:
    base-path: ${dcsa.url.prefix:}
  upload_config_path: config/uploaded
  callback_port: 9999
  callback_uri: http://localhost
  test_data: config/v2/testdata.json
  event_subscription_simulation: 'true'
  config_data: config/v2/config.json
  test_suite_name: TNT-TestSuite.xml
  api_root_uri: http://localhost:9090
  callback_wait: 3000
  notificationTriggerTime: 1000
  externalCallback: false
  event_path: config/uploaded/events/v2/EquipmentEvent.json

auth0:
  audience: localhost
  enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    # swagger-ui custom path
    path: /docs

server:
  port: ${SERVER_PORT:9092}

report:
  theme: standard
  file:
    name: Consumer-CTK-Report
    location: reports
  title: Consumer Report
  timeline:
    enabled: 'false'
  time:
    stamp:
      format: yyyy-MM-dd_HH-mm-ss
  author: Masum Islam
  company: DCSA
  name: Consumer CTK Report
extent:
  reporter:
    spark:
      start: 'true'

management:
  endpoints:
    web:
      exposure:
        include: '*'
